# Generated by Django 5.0.14 on 2025-10-31 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 22, 35, 48, 503529, tzinfo=datetime.timezone.utc)),
        ),
    ]
